# Generated by Django 2.0 on 2020-02-12 19:21

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', ckeditor.fields.RichTextField()),
                ('resim', models.ImageField(blank=True, null=True, upload_to='')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='yayımlanma_tarihi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='süperkullanıcı')),
            ],
            options={
                'ordering': ['-publishing_date'],
            },
        ),
    ]
